image: node:latest

stages:
  - manual_deploy_dev
  - manual_deploy_prod
  - e2e_dev
  - quality_check
  - deploy_dev
  - deploy_prod


#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - /root/.cache/Cypress
#    - .cache/*
#    - cache/Cypress
#    - node_modules
#    - build


quality_check:
  stage: quality_check
  script:
    - yarn
    - yarn lint:global
    - yarn test


e2e_dev:
  stage: e2e_dev
  environment: dev
  extends: .e2e


.e2e:
  image: cypress/browsers:node14.17.6-chrome100-ff98
  stage: e2e
  script:
    - yarn
    - yarn start:$CI_ENVIRONMENT_NAME &
    - ./wait-for-server.sh
    - npx cypress run --record --key 08ccf44d-e082-4aa7-a534-616f7aa33e1d --parallel --browser chrome --group "e2e - Chrome"


deploy_dev:
  stage: deploy_dev
  environment: dev
  only:
    - master
  extends: .deploy

manual_deploy_dev:
  stage: manual_deploy_dev
  extends: .deploy
  environment: dev
  when: manual

manual_deploy_prod:
  stage: manual_deploy_prod
  extends: .deploy
  environment: prod
  when: manual

deploy_prod:
  stage: deploy_prod
  environment: prod
  only:
    - master
  extends: .deploy
  when: manual

.deploy:
  script:
    - npm install -g firebase-tools
    - yarn install
    - yarn build:$CI_ENVIRONMENT_NAME
    - firebase use --token $FIREBASE_TOKEN $CI_ENVIRONMENT_NAME
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
