export default [
  'American Samoa',
  'California',
  'Colorado',
  'Federated States of Micronesia',
  'Guam',
  'Hawaii',
  'Illinois',
  'Marshall Islands',
  'Massachusetts',
  'Montana',
  'New Hampshire',
  'North Dakota',
  'Northern Mariana Islands',
  'Palau',
  'Pennsylvania',
  'Puerto Rico',
  'Texas',
  'Virgin Island',
  'Virginia',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];
